nome = input('Digite seu nome completo:').strip() .upper()
#print(nome.split())
lista = (nome.split())
print('primeiro nome: {}'.format(lista[0]))
print('Último nome: {}'.format(lista[len(lista) - 1]))
